- name: Configurer VyOS
  hosts: vyos
  gather_facts: no
  collections:
    - vyos.vyos

  roles:
    - vyos_config

- name: Configurer firewall + IDS
  hosts: opnsense
  gather_facts: no
  module_defaults:
    group/ansibleguy.opnsense.all:
      firewall: '192.168.5.1'
      api_credential_file: 'api-key.key'
      ssl_verify: false
    ansibleguy.opnsense.list:
      target: 'rule'

  roles:
    - firewall_dmz
    - firewall_lan
    - firewall_adm
    - firewall_allow_dmz
    - ids

