- name: Configure IDS/IPS (passif ou bloquant)
  ansibleguy.opnsense.ids_general:
    interfaces: "{{ ids_interfaces }}"
    enabled: true
    block: "{{ enable_blocking | default(false) }}"
    pattern_matcher: "ac"
    profile: "low"
    local_networks: "{{ ids_local_networks }}"
    log_rotate: "daily"
    log_retention: 14
    syslog: true
    log_level: "info"
    reload: "{{ not enable_blocking }}"
  when: enable_blocking or not enable_blocking

- name: Show current IDS general config
  ansibleguy.opnsense.list:
    target: "ids_general"
  register: existing_settings

- name: Print IDS General settings
  debug:
    var: existing_settings.data

- name: Enable & reload ruleset
  ansibleguy.opnsense.ids_ruleset:
    name: "{{ ruleset_name }}"
    enabled: true
    reload: true

- name: Disable ruleset
  ansibleguy.opnsense.ids_ruleset:
    name: "{{ ruleset_name }}"
    enabled: false

- name: List all rulesets
  ansibleguy.opnsense.list:
    target: "ids_ruleset"
  register: existing_rulesets

- name: Print rulesets
  debug:
    var: existing_rulesets.data

- name: Get IDS status
  ansibleguy.opnsense.ids_action:
    action: "status"

- name: Pull IDS alert logs
  ansibleguy.opnsense.ids_action:
    action: "get_alert_logs"
  register: ids_logs

- name: Print IDS alert logs
  debug:
    var: ids_logs.data

- name: Reload IDS rules
  ansibleguy.opnsense.ids_action:
    action: "reload_rules"

- name: Update IDS rules
  ansibleguy.opnsense.ids_action:
    action: "update_rules"
