- name: Block all to DMZ
  ansibleguy.opnsense.rule:
    source_net: '192.168.4.15/24'
    destination_net: '192.168.4.1/24'
    destination_port: 'any'
    protocol: 'TCP'
    description: 'Block all to DMZ'
    match_fields: ['description']
    sequence: 1
    action: 'block'
    quick: true
    interface: 'opt1'
    direction: 'in'
    ip_protocol: 'inet'
    state: 'present'
    enabled: true
    debug: false
